-- 0003_palettes.sql — colour seasons, sub-seasons, palette colours,
-- cosmetic recommendations, favourite colours.

create table public.colour_seasons (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,40}$'),
  name text not null check (char_length(name) between 2 and 80),
  tagline text not null default '',
  description text not null default '',
  -- Typical signals shown on public season pages (temperature, value,
  -- chroma, contrast descriptors).
  characteristics jsonb not null default '{}'::jsonb,
  display_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_colour_seasons_updated_at
  before update on public.colour_seasons
  for each row execute function public.set_updated_at();

create table public.colour_subseasons (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.colour_seasons (id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,40}$'),
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '',
  characteristics jsonb not null default '{}'::jsonb,
  display_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_colour_subseasons_season on public.colour_subseasons (season_id);

create trigger trg_colour_subseasons_updated_at
  before update on public.colour_subseasons
  for each row execute function public.set_updated_at();

create table public.palette_colours (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.colour_seasons (id) on delete cascade,
  -- Optional narrowing to a sub-season; season-wide colours keep this null.
  subseason_id uuid references public.colour_subseasons (id) on delete set null,
  name text not null check (char_length(name) between 2 and 80),
  hex char(7) not null check (hex ~ '^#[0-9a-f]{6}$'),
  -- CIE Lab (D65) is stored so CIEDE2000 product matching never recomputes
  -- from sRGB at query time. Values generated by scripts/generate_seed.py.
  lab_l numeric(6, 2) not null check (lab_l between 0 and 100),
  lab_a numeric(6, 2) not null check (lab_a between -128 and 128),
  lab_b numeric(6, 2) not null check (lab_b between -128 and 128),
  palette_group text not null check (
    palette_group in (
      'neutrals', 'core', 'accents', 'formal', 'casual',
      'accessories', 'headwear', 'cautious'
    )
  ),
  colour_family text not null default '',
  recommended_use text not null default '',
  priority integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_palette_colours_season_group
  on public.palette_colours (season_id, palette_group, priority);
create index idx_palette_colours_subseason
  on public.palette_colours (subseason_id) where subseason_id is not null;

create trigger trg_palette_colours_updated_at
  before update on public.palette_colours
  for each row execute function public.set_updated_at();

create table public.cosmetic_recommendations (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.colour_seasons (id) on delete cascade,
  subseason_id uuid references public.colour_subseasons (id) on delete set null,
  product_type text not null check (
    product_type in (
      'lipstick', 'blusher', 'eyeshadow', 'eyeliner', 'highlighter', 'foundation'
    )
  ),
  name text not null check (char_length(name) between 2 and 80),
  hex char(7) not null check (hex ~ '^#[0-9a-f]{6}$'),
  intensity text not null default 'medium' check (intensity in ('soft', 'medium', 'bold')),
  occasion text not null default 'any' check (occasion in ('day', 'evening', 'any')),
  usage_note text not null default '',
  priority integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_cosmetics_season_type
  on public.cosmetic_recommendations (season_id, product_type, priority);

create trigger trg_cosmetic_recommendations_updated_at
  before update on public.cosmetic_recommendations
  for each row execute function public.set_updated_at();

create table public.user_favourite_colours (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  palette_colour_id uuid not null references public.palette_colours (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, palette_colour_id)
);

create index idx_user_favourite_colours_user
  on public.user_favourite_colours (user_id, created_at desc);
